# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T02:59:14+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class State(Enum):
    STATE_UNSPECIFIED = 'STATE_UNSPECIFIED'
    CREATING = 'CREATING'
    CREATED = 'CREATED'
    DELETING = 'DELETING'


class AwsAccessKey(BaseModel):
    accessKeyId: Optional[str] = Field(None, description='Required. AWS access key ID.')
    secretAccessKey: Optional[str] = Field(
        None,
        description='Required. AWS secret access key. This field is not returned in RPC responses.',
    )


class AwsS3Data(BaseModel):
    awsAccessKey: Optional[AwsAccessKey] = Field(
        None,
        description='Input only. AWS access key used to sign the API requests to the AWS S3 bucket. Permissions on the bucket must be granted to the access ID of the AWS access key. For information on our data retention policy for user credentials, see [User credentials](/storage-transfer/docs/data-retention#user-credentials).',
    )
    bucketName: Optional[str] = Field(
        None,
        description='Required. S3 Bucket name (see [Creating a bucket](https://docs.aws.amazon.com/AmazonS3/latest/dev/create-bucket-get-location-example.html)).',
    )
    path: Optional[str] = Field(
        None,
        description="Root path to transfer objects. Must be an empty string or full path name that ends with a '/'. This field is treated as an object prefix. As such, it should generally not begin with a '/'.",
    )
    roleArn: Optional[str] = Field(
        None,
        description='The Amazon Resource Name (ARN) of the role to support temporary credentials via `AssumeRoleWithWebIdentity`. For more information about ARNs, see [IAM ARNs](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_identifiers.html#identifiers-arns). When a role ARN is provided, Transfer Service fetches temporary credentials for the session using a `AssumeRoleWithWebIdentity` call for the provided role using the GoogleServiceAccount for this project.',
    )


class AzureCredentials(BaseModel):
    sasToken: Optional[str] = Field(
        None,
        description='Required. Azure shared access signature (SAS). For more information about SAS, see [Grant limited access to Azure Storage resources using shared access signatures (SAS)](https://docs.microsoft.com/en-us/azure/storage/common/storage-sas-overview).',
    )


class BandwidthLimit(BaseModel):
    limitMbps: Optional[str] = Field(
        None,
        description='Bandwidth rate in megabytes per second, distributed across all the agents in the pool.',
    )


class CancelOperationRequest(BaseModel):
    pass


class Date(BaseModel):
    day: Optional[int] = Field(
        None,
        description="Day of a month. Must be from 1 to 31 and valid for the year and month, or 0 to specify a year by itself or a year and month where the day isn't significant.",
    )
    month: Optional[int] = Field(
        None,
        description='Month of a year. Must be from 1 to 12, or 0 to specify a year without a month and day.',
    )
    year: Optional[int] = Field(
        None,
        description='Year of the date. Must be from 1 to 9999, or 0 to specify a date without a year.',
    )


class Empty(BaseModel):
    pass


class ErrorLogEntry(BaseModel):
    errorDetails: Optional[List[str]] = Field(
        None, description='A list of messages that carry the error details.'
    )
    url: Optional[str] = Field(
        None,
        description='Required. A URL that refers to the target (a data source, a data sink, or an object) with which the error is associated.',
    )


class ErrorCode(Enum):
    OK = 'OK'
    CANCELLED = 'CANCELLED'
    UNKNOWN = 'UNKNOWN'
    INVALID_ARGUMENT = 'INVALID_ARGUMENT'
    DEADLINE_EXCEEDED = 'DEADLINE_EXCEEDED'
    NOT_FOUND = 'NOT_FOUND'
    ALREADY_EXISTS = 'ALREADY_EXISTS'
    PERMISSION_DENIED = 'PERMISSION_DENIED'
    UNAUTHENTICATED = 'UNAUTHENTICATED'
    RESOURCE_EXHAUSTED = 'RESOURCE_EXHAUSTED'
    FAILED_PRECONDITION = 'FAILED_PRECONDITION'
    ABORTED = 'ABORTED'
    OUT_OF_RANGE = 'OUT_OF_RANGE'
    UNIMPLEMENTED = 'UNIMPLEMENTED'
    INTERNAL = 'INTERNAL'
    UNAVAILABLE = 'UNAVAILABLE'
    DATA_LOSS = 'DATA_LOSS'


class ErrorSummary(BaseModel):
    errorCode: Optional[ErrorCode] = Field(None, description='Required.')
    errorCount: Optional[str] = Field(
        None, description='Required. Count of this type of error.'
    )
    errorLogEntries: Optional[List[ErrorLogEntry]] = Field(
        None,
        description='Error samples. At most 5 error log entries are recorded for a given error code for a single transfer operation.',
    )


class EventStream(BaseModel):
    eventStreamExpirationTime: Optional[str] = Field(
        None,
        description='Specifies the data and time at which Storage Transfer Service stops listening for events from this stream. After this time, any transfers in progress will complete, but no new transfers are initiated.',
    )
    eventStreamStartTime: Optional[str] = Field(
        None,
        description='Specifies the date and time that Storage Transfer Service starts listening for events from this stream. If no start time is specified or start time is in the past, Storage Transfer Service starts listening immediately.',
    )
    name: Optional[str] = Field(
        None,
        description="Required. Specifies a unique name of the resource such as AWS SQS ARN in the form 'arn:aws:sqs:region:account_id:queue_name', or Pub/Sub subscription resource name in the form 'projects/{project}/subscriptions/{sub}'.",
    )


class GcsData(BaseModel):
    bucketName: Optional[str] = Field(
        None,
        description='Required. Cloud Storage bucket name. Must meet [Bucket Name Requirements](/storage/docs/naming#requirements).',
    )
    path: Optional[str] = Field(
        None,
        description="Root path to transfer objects. Must be an empty string or full path name that ends with a '/'. This field is treated as an object prefix. As such, it should generally not begin with a '/'. The root path value must meet [Object Name Requirements](/storage/docs/naming#objectnames).",
    )


class GoogleServiceAccount(BaseModel):
    accountEmail: Optional[str] = Field(
        None, description='Email address of the service account.'
    )
    subjectId: Optional[str] = Field(
        None, description='Unique identifier for the service account.'
    )


class HttpData(BaseModel):
    listUrl: Optional[str] = Field(
        None,
        description='Required. The URL that points to the file that stores the object list entries. This file must allow public access. Currently, only URLs with HTTP and HTTPS schemes are supported.',
    )


class LogActionState(Enum):
    LOGGABLE_ACTION_STATE_UNSPECIFIED = 'LOGGABLE_ACTION_STATE_UNSPECIFIED'
    SUCCEEDED = 'SUCCEEDED'
    FAILED = 'FAILED'


class LogAction(Enum):
    LOGGABLE_ACTION_UNSPECIFIED = 'LOGGABLE_ACTION_UNSPECIFIED'
    FIND = 'FIND'
    DELETE = 'DELETE'
    COPY = 'COPY'


class LoggingConfig(BaseModel):
    enableOnpremGcsTransferLogs: Optional[bool] = Field(
        None,
        description='For transfers with a PosixFilesystem source, this option enables the Cloud Storage transfer logs for this transfer.',
    )
    logActionStates: Optional[List[LogActionState]] = Field(
        None,
        description='States in which `log_actions` are logged. If empty, no logs are generated. Not supported for transfers with PosixFilesystem data sources; use enable_onprem_gcs_transfer_logs instead.',
    )
    logActions: Optional[List[LogAction]] = Field(
        None,
        description='Specifies the actions to be logged. If empty, no logs are generated. Not supported for transfers with PosixFilesystem data sources; use enable_onprem_gcs_transfer_logs instead.',
    )


class Acl(Enum):
    ACL_UNSPECIFIED = 'ACL_UNSPECIFIED'
    ACL_DESTINATION_BUCKET_DEFAULT = 'ACL_DESTINATION_BUCKET_DEFAULT'
    ACL_PRESERVE = 'ACL_PRESERVE'


class Gid(Enum):
    GID_UNSPECIFIED = 'GID_UNSPECIFIED'
    GID_SKIP = 'GID_SKIP'
    GID_NUMBER = 'GID_NUMBER'


class KmsKey(Enum):
    KMS_KEY_UNSPECIFIED = 'KMS_KEY_UNSPECIFIED'
    KMS_KEY_DESTINATION_BUCKET_DEFAULT = 'KMS_KEY_DESTINATION_BUCKET_DEFAULT'
    KMS_KEY_PRESERVE = 'KMS_KEY_PRESERVE'


class Mode(Enum):
    MODE_UNSPECIFIED = 'MODE_UNSPECIFIED'
    MODE_SKIP = 'MODE_SKIP'
    MODE_PRESERVE = 'MODE_PRESERVE'


class StorageClass(Enum):
    STORAGE_CLASS_UNSPECIFIED = 'STORAGE_CLASS_UNSPECIFIED'
    STORAGE_CLASS_DESTINATION_BUCKET_DEFAULT = (
        'STORAGE_CLASS_DESTINATION_BUCKET_DEFAULT'
    )
    STORAGE_CLASS_PRESERVE = 'STORAGE_CLASS_PRESERVE'
    STORAGE_CLASS_STANDARD = 'STORAGE_CLASS_STANDARD'
    STORAGE_CLASS_NEARLINE = 'STORAGE_CLASS_NEARLINE'
    STORAGE_CLASS_COLDLINE = 'STORAGE_CLASS_COLDLINE'
    STORAGE_CLASS_ARCHIVE = 'STORAGE_CLASS_ARCHIVE'


class Symlink(Enum):
    SYMLINK_UNSPECIFIED = 'SYMLINK_UNSPECIFIED'
    SYMLINK_SKIP = 'SYMLINK_SKIP'
    SYMLINK_PRESERVE = 'SYMLINK_PRESERVE'


class TemporaryHold(Enum):
    TEMPORARY_HOLD_UNSPECIFIED = 'TEMPORARY_HOLD_UNSPECIFIED'
    TEMPORARY_HOLD_SKIP = 'TEMPORARY_HOLD_SKIP'
    TEMPORARY_HOLD_PRESERVE = 'TEMPORARY_HOLD_PRESERVE'


class TimeCreated(Enum):
    TIME_CREATED_UNSPECIFIED = 'TIME_CREATED_UNSPECIFIED'
    TIME_CREATED_SKIP = 'TIME_CREATED_SKIP'
    TIME_CREATED_PRESERVE_AS_CUSTOM_TIME = 'TIME_CREATED_PRESERVE_AS_CUSTOM_TIME'


class Uid(Enum):
    UID_UNSPECIFIED = 'UID_UNSPECIFIED'
    UID_SKIP = 'UID_SKIP'
    UID_NUMBER = 'UID_NUMBER'


class MetadataOptions(BaseModel):
    acl: Optional[Acl] = Field(
        None,
        description="Specifies how each object's ACLs should be preserved for transfers between Google Cloud Storage buckets. If unspecified, the default behavior is the same as ACL_DESTINATION_BUCKET_DEFAULT.",
    )
    gid: Optional[Gid] = Field(
        None,
        description="Specifies how each file's POSIX group ID (GID) attribute should be handled by the transfer. By default, GID is not preserved. Only applicable to transfers involving POSIX file systems, and ignored for other transfers.",
    )
    kmsKey: Optional[KmsKey] = Field(
        None,
        description="Specifies how each object's Cloud KMS customer-managed encryption key (CMEK) is preserved for transfers between Google Cloud Storage buckets. If unspecified, the default behavior is the same as KMS_KEY_DESTINATION_BUCKET_DEFAULT.",
    )
    mode: Optional[Mode] = Field(
        None,
        description="Specifies how each file's mode attribute should be handled by the transfer. By default, mode is not preserved. Only applicable to transfers involving POSIX file systems, and ignored for other transfers.",
    )
    storageClass: Optional[StorageClass] = Field(
        None,
        description='Specifies the storage class to set on objects being transferred to Google Cloud Storage buckets. If unspecified, the default behavior is the same as STORAGE_CLASS_DESTINATION_BUCKET_DEFAULT.',
    )
    symlink: Optional[Symlink] = Field(
        None,
        description='Specifies how symlinks should be handled by the transfer. By default, symlinks are not preserved. Only applicable to transfers involving POSIX file systems, and ignored for other transfers.',
    )
    temporaryHold: Optional[TemporaryHold] = Field(
        None,
        description="Specifies how each object's temporary hold status should be preserved for transfers between Google Cloud Storage buckets. If unspecified, the default behavior is the same as TEMPORARY_HOLD_PRESERVE.",
    )
    timeCreated: Optional[TimeCreated] = Field(
        None,
        description="Specifies how each object's `timeCreated` metadata is preserved for transfers between Google Cloud Storage buckets. If unspecified, the default behavior is the same as TIME_CREATED_SKIP.",
    )
    uid: Optional[Uid] = Field(
        None,
        description="Specifies how each file's POSIX user ID (UID) attribute should be handled by the transfer. By default, UID is not preserved. Only applicable to transfers involving POSIX file systems, and ignored for other transfers.",
    )


class EventType(Enum):
    EVENT_TYPE_UNSPECIFIED = 'EVENT_TYPE_UNSPECIFIED'
    TRANSFER_OPERATION_SUCCESS = 'TRANSFER_OPERATION_SUCCESS'
    TRANSFER_OPERATION_FAILED = 'TRANSFER_OPERATION_FAILED'
    TRANSFER_OPERATION_ABORTED = 'TRANSFER_OPERATION_ABORTED'


class PayloadFormat(Enum):
    PAYLOAD_FORMAT_UNSPECIFIED = 'PAYLOAD_FORMAT_UNSPECIFIED'
    NONE = 'NONE'
    JSON = 'JSON'


class NotificationConfig(BaseModel):
    eventTypes: Optional[List[EventType]] = Field(
        None,
        description='Event types for which a notification is desired. If empty, send notifications for all event types.',
    )
    payloadFormat: Optional[PayloadFormat] = Field(
        None,
        description='Required. The desired format of the notification message payloads.',
    )
    pubsubTopic: Optional[str] = Field(
        None,
        description='Required. The `Topic.name` of the Pub/Sub topic to which to publish notifications. Must be of the format: `projects/{project}/topics/{topic}`. Not matching this format results in an INVALID_ARGUMENT error.',
    )


class ObjectConditions(BaseModel):
    excludePrefixes: Optional[List[str]] = Field(
        None,
        description='If you specify `exclude_prefixes`, Storage Transfer Service uses the items in the `exclude_prefixes` array to determine which objects to exclude from a transfer. Objects must not start with one of the matching `exclude_prefixes` for inclusion in a transfer. The following are requirements of `exclude_prefixes`: * Each exclude-prefix can contain any sequence of Unicode characters, to a max length of 1024 bytes when UTF8-encoded, and must not contain Carriage Return or Line Feed characters. Wildcard matching and regular expression matching are not supported. * Each exclude-prefix must omit the leading slash. For example, to exclude the object `s3://my-aws-bucket/logs/y=2015/requests.gz`, specify the exclude-prefix as `logs/y=2015/requests.gz`. * None of the exclude-prefix values can be empty, if specified. * Each exclude-prefix must exclude a distinct portion of the object namespace. No exclude-prefix may be a prefix of another exclude-prefix. * If include_prefixes is specified, then each exclude-prefix must start with the value of a path explicitly included by `include_prefixes`. The max size of `exclude_prefixes` is 1000. For more information, see [Filtering objects from transfers](/storage-transfer/docs/filtering-objects-from-transfers).',
    )
    includePrefixes: Optional[List[str]] = Field(
        None,
        description='If you specify `include_prefixes`, Storage Transfer Service uses the items in the `include_prefixes` array to determine which objects to include in a transfer. Objects must start with one of the matching `include_prefixes` for inclusion in the transfer. If exclude_prefixes is specified, objects must not start with any of the `exclude_prefixes` specified for inclusion in the transfer. The following are requirements of `include_prefixes`: * Each include-prefix can contain any sequence of Unicode characters, to a max length of 1024 bytes when UTF8-encoded, and must not contain Carriage Return or Line Feed characters. Wildcard matching and regular expression matching are not supported. * Each include-prefix must omit the leading slash. For example, to include the object `s3://my-aws-bucket/logs/y=2015/requests.gz`, specify the include-prefix as `logs/y=2015/requests.gz`. * None of the include-prefix values can be empty, if specified. * Each include-prefix must include a distinct portion of the object namespace. No include-prefix may be a prefix of another include-prefix. The max size of `include_prefixes` is 1000. For more information, see [Filtering objects from transfers](/storage-transfer/docs/filtering-objects-from-transfers).',
    )
    lastModifiedBefore: Optional[str] = Field(
        None,
        description='If specified, only objects with a "last modification time" before this timestamp and objects that don\'t have a "last modification time" are transferred.',
    )
    lastModifiedSince: Optional[str] = Field(
        None,
        description='If specified, only objects with a "last modification time" on or after this timestamp and objects that don\'t have a "last modification time" are transferred. The `last_modified_since` and `last_modified_before` fields can be used together for chunked data processing. For example, consider a script that processes each day\'s worth of data at a time. For that you\'d set each of the fields as follows: * `last_modified_since` to the start of the day * `last_modified_before` to the end of the day',
    )
    maxTimeElapsedSinceLastModification: Optional[str] = Field(
        None,
        description='Ensures that objects are not transferred if a specific maximum time has elapsed since the "last modification time". When a TransferOperation begins, objects with a "last modification time" are transferred only if the elapsed time between the start_time of the `TransferOperation`and the "last modification time" of the object is less than the value of max_time_elapsed_since_last_modification`. Objects that do not have a "last modification time" are also transferred.',
    )
    minTimeElapsedSinceLastModification: Optional[str] = Field(
        None,
        description='Ensures that objects are not transferred until a specific minimum time has elapsed after the "last modification time". When a TransferOperation begins, objects with a "last modification time" are transferred only if the elapsed time between the start_time of the `TransferOperation` and the "last modification time" of the object is equal to or greater than the value of min_time_elapsed_since_last_modification`. Objects that do not have a "last modification time" are also transferred.',
    )


class PauseTransferOperationRequest(BaseModel):
    pass


class PosixFilesystem(BaseModel):
    rootDirectory: Optional[str] = Field(
        None, description='Root directory path to the filesystem.'
    )


class ResumeTransferOperationRequest(BaseModel):
    pass


class RunTransferJobRequest(BaseModel):
    projectId: Optional[str] = Field(
        None,
        description='Required. The ID of the Google Cloud project that owns the transfer job.',
    )


class AuthMethod(Enum):
    AUTH_METHOD_UNSPECIFIED = 'AUTH_METHOD_UNSPECIFIED'
    AUTH_METHOD_AWS_SIGNATURE_V4 = 'AUTH_METHOD_AWS_SIGNATURE_V4'
    AUTH_METHOD_AWS_SIGNATURE_V2 = 'AUTH_METHOD_AWS_SIGNATURE_V2'


class ListApi(Enum):
    LIST_API_UNSPECIFIED = 'LIST_API_UNSPECIFIED'
    LIST_OBJECTS_V2 = 'LIST_OBJECTS_V2'
    LIST_OBJECTS = 'LIST_OBJECTS'


class Protocol(Enum):
    NETWORK_PROTOCOL_UNSPECIFIED = 'NETWORK_PROTOCOL_UNSPECIFIED'
    NETWORK_PROTOCOL_HTTPS = 'NETWORK_PROTOCOL_HTTPS'
    NETWORK_PROTOCOL_HTTP = 'NETWORK_PROTOCOL_HTTP'


class RequestModel(Enum):
    REQUEST_MODEL_UNSPECIFIED = 'REQUEST_MODEL_UNSPECIFIED'
    REQUEST_MODEL_VIRTUAL_HOSTED_STYLE = 'REQUEST_MODEL_VIRTUAL_HOSTED_STYLE'
    REQUEST_MODEL_PATH_STYLE = 'REQUEST_MODEL_PATH_STYLE'


class S3CompatibleMetadata(BaseModel):
    authMethod: Optional[AuthMethod] = Field(
        None,
        description='Specifies the authentication and authorization method used by the storage service. When not specified, Transfer Service will attempt to determine right auth method to use.',
    )
    listApi: Optional[ListApi] = Field(
        None,
        description='The Listing API to use for discovering objects. When not specified, Transfer Service will attempt to determine the right API to use.',
    )
    protocol: Optional[Protocol] = Field(
        None,
        description='Specifies the network protocol of the agent. When not specified, the default value of NetworkProtocol NETWORK_PROTOCOL_HTTPS is used.',
    )
    requestModel: Optional[RequestModel] = Field(
        None,
        description='Specifies the API request model used to call the storage service. When not specified, the default value of RequestModel REQUEST_MODEL_VIRTUAL_HOSTED_STYLE is used.',
    )


class Status(BaseModel):
    code: Optional[int] = Field(
        None,
        description='The status code, which should be an enum value of google.rpc.Code.',
    )
    details: Optional[List[Dict[str, Any]]] = Field(
        None,
        description='A list of messages that carry the error details. There is a common set of message types for APIs to use.',
    )
    message: Optional[str] = Field(
        None,
        description='A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the google.rpc.Status.details field, or localized by the client.',
    )


class TimeOfDay(BaseModel):
    hours: Optional[int] = Field(
        None,
        description='Hours of day in 24 hour format. Should be from 0 to 23. An API may choose to allow the value "24:00:00" for scenarios like business closing time.',
    )
    minutes: Optional[int] = Field(
        None, description='Minutes of hour of day. Must be from 0 to 59.'
    )
    nanos: Optional[int] = Field(
        None,
        description='Fractions of seconds in nanoseconds. Must be from 0 to 999,999,999.',
    )
    seconds: Optional[int] = Field(
        None,
        description='Seconds of minutes of the time. Must normally be from 0 to 59. An API may allow the value 60 if it allows leap-seconds.',
    )


class TransferCounters(BaseModel):
    bytesCopiedToSink: Optional[str] = Field(
        None, description='Bytes that are copied to the data sink.'
    )
    bytesDeletedFromSink: Optional[str] = Field(
        None, description='Bytes that are deleted from the data sink.'
    )
    bytesDeletedFromSource: Optional[str] = Field(
        None, description='Bytes that are deleted from the data source.'
    )
    bytesFailedToDeleteFromSink: Optional[str] = Field(
        None, description='Bytes that failed to be deleted from the data sink.'
    )
    bytesFoundFromSource: Optional[str] = Field(
        None,
        description='Bytes found in the data source that are scheduled to be transferred, excluding any that are filtered based on object conditions or skipped due to sync.',
    )
    bytesFoundOnlyFromSink: Optional[str] = Field(
        None,
        description='Bytes found only in the data sink that are scheduled to be deleted.',
    )
    bytesFromSourceFailed: Optional[str] = Field(
        None,
        description='Bytes in the data source that failed to be transferred or that failed to be deleted after being transferred.',
    )
    bytesFromSourceSkippedBySync: Optional[str] = Field(
        None,
        description='Bytes in the data source that are not transferred because they already exist in the data sink.',
    )
    directoriesFailedToListFromSource: Optional[str] = Field(
        None,
        description='For transfers involving PosixFilesystem only. Number of listing failures for each directory found at the source. Potential failures when listing a directory include permission failure or block failure. If listing a directory fails, no files in the directory are transferred.',
    )
    directoriesFoundFromSource: Optional[str] = Field(
        None,
        description='For transfers involving PosixFilesystem only. Number of directories found while listing. For example, if the root directory of the transfer is `base/` and there are two other directories, `a/` and `b/` under this directory, the count after listing `base/`, `base/a/` and `base/b/` is 3.',
    )
    directoriesSuccessfullyListedFromSource: Optional[str] = Field(
        None,
        description='For transfers involving PosixFilesystem only. Number of successful listings for each directory found at the source.',
    )
    intermediateObjectsCleanedUp: Optional[str] = Field(
        None, description='Number of successfully cleaned up intermediate objects.'
    )
    intermediateObjectsFailedCleanedUp: Optional[str] = Field(
        None, description='Number of intermediate objects failed cleaned up.'
    )
    objectsCopiedToSink: Optional[str] = Field(
        None, description='Objects that are copied to the data sink.'
    )
    objectsDeletedFromSink: Optional[str] = Field(
        None, description='Objects that are deleted from the data sink.'
    )
    objectsDeletedFromSource: Optional[str] = Field(
        None, description='Objects that are deleted from the data source.'
    )
    objectsFailedToDeleteFromSink: Optional[str] = Field(
        None, description='Objects that failed to be deleted from the data sink.'
    )
    objectsFoundFromSource: Optional[str] = Field(
        None,
        description='Objects found in the data source that are scheduled to be transferred, excluding any that are filtered based on object conditions or skipped due to sync.',
    )
    objectsFoundOnlyFromSink: Optional[str] = Field(
        None,
        description='Objects found only in the data sink that are scheduled to be deleted.',
    )
    objectsFromSourceFailed: Optional[str] = Field(
        None,
        description='Objects in the data source that failed to be transferred or that failed to be deleted after being transferred.',
    )
    objectsFromSourceSkippedBySync: Optional[str] = Field(
        None,
        description='Objects in the data source that are not transferred because they already exist in the data sink.',
    )


class Status1(Enum):
    STATUS_UNSPECIFIED = 'STATUS_UNSPECIFIED'
    ENABLED = 'ENABLED'
    DISABLED = 'DISABLED'
    DELETED = 'DELETED'


class TransferManifest(BaseModel):
    location: Optional[str] = Field(
        None,
        description='Specifies the path to the manifest in Cloud Storage. The Google-managed service account for the transfer must have `storage.objects.get` permission for this object. An example path is `gs://bucket_name/path/manifest.csv`.',
    )


class Status2(Enum):
    STATUS_UNSPECIFIED = 'STATUS_UNSPECIFIED'
    IN_PROGRESS = 'IN_PROGRESS'
    PAUSED = 'PAUSED'
    SUCCESS = 'SUCCESS'
    FAILED = 'FAILED'
    ABORTED = 'ABORTED'
    QUEUED = 'QUEUED'
    SUSPENDING = 'SUSPENDING'


class OverwriteWhen(Enum):
    OVERWRITE_WHEN_UNSPECIFIED = 'OVERWRITE_WHEN_UNSPECIFIED'
    DIFFERENT = 'DIFFERENT'
    NEVER = 'NEVER'
    ALWAYS = 'ALWAYS'


class TransferOptions(BaseModel):
    deleteObjectsFromSourceAfterTransfer: Optional[bool] = Field(
        None,
        description='Whether objects should be deleted from the source after they are transferred to the sink. **Note:** This option and delete_objects_unique_in_sink are mutually exclusive.',
    )
    deleteObjectsUniqueInSink: Optional[bool] = Field(
        None,
        description='Whether objects that exist only in the sink should be deleted. **Note:** This option and delete_objects_from_source_after_transfer are mutually exclusive.',
    )
    metadataOptions: Optional[MetadataOptions] = Field(
        None, description='Represents the selected metadata options for a transfer job.'
    )
    overwriteObjectsAlreadyExistingInSink: Optional[bool] = Field(
        None,
        description='When to overwrite objects that already exist in the sink. The default is that only objects that are different from the source are ovewritten. If true, all objects in the sink whose name matches an object in the source are overwritten with the source object.',
    )
    overwriteWhen: Optional[OverwriteWhen] = Field(
        None,
        description='When to overwrite objects that already exist in the sink. If not set, overwrite behavior is determined by overwrite_objects_already_existing_in_sink.',
    )


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class AgentPool(BaseModel):
    bandwidthLimit: Optional[BandwidthLimit] = Field(
        None,
        description="Specifies the bandwidth limit details. If this field is unspecified, the default value is set as 'No Limit'.",
    )
    displayName: Optional[str] = Field(
        None, description='Specifies the client-specified AgentPool description.'
    )
    name: Optional[str] = Field(
        None,
        description='Required. Specifies a unique string that identifies the agent pool. Format: `projects/{project_id}/agentPools/{agent_pool_id}`',
    )
    state: Optional[State] = Field(
        None, description='Output only. Specifies the state of the AgentPool.'
    )


class AwsS3CompatibleData(BaseModel):
    bucketName: Optional[str] = Field(
        None, description='Required. Specifies the name of the bucket.'
    )
    endpoint: Optional[str] = Field(
        None, description='Required. Specifies the endpoint of the storage service.'
    )
    path: Optional[str] = Field(
        None,
        description="Specifies the root path to transfer objects. Must be an empty string or full path name that ends with a '/'. This field is treated as an object prefix. As such, it should generally not begin with a '/'.",
    )
    region: Optional[str] = Field(
        None,
        description='Specifies the region to sign requests with. This can be left blank if requests should be signed with an empty region.',
    )
    s3Metadata: Optional[S3CompatibleMetadata] = Field(
        None, description='A S3 compatible metadata.'
    )


class AzureBlobStorageData(BaseModel):
    azureCredentials: Optional[AzureCredentials] = Field(
        None,
        description='Required. Input only. Credentials used to authenticate API requests to Azure. For information on our data retention policy for user credentials, see [User credentials](/storage-transfer/docs/data-retention#user-credentials).',
    )
    container: Optional[str] = Field(
        None,
        description='Required. The container to transfer from the Azure Storage account.',
    )
    path: Optional[str] = Field(
        None,
        description="Root path to transfer objects. Must be an empty string or full path name that ends with a '/'. This field is treated as an object prefix. As such, it should generally not begin with a '/'.",
    )
    storageAccount: Optional[str] = Field(
        None, description='Required. The name of the Azure Storage account.'
    )


class ListAgentPoolsResponse(BaseModel):
    agentPools: Optional[List[AgentPool]] = Field(
        None, description='A list of agent pools.'
    )
    nextPageToken: Optional[str] = Field(None, description='The list next page token.')


class Operation(BaseModel):
    done: Optional[bool] = Field(
        None,
        description='If the value is `false`, it means the operation is still in progress. If `true`, the operation is completed, and either `error` or `response` is available.',
    )
    error: Optional[Status] = Field(
        None,
        description='The error result of the operation in case of failure or cancellation.',
    )
    metadata: Optional[Dict[str, Any]] = Field(
        None,
        description='Represents the transfer operation object. To request a TransferOperation object, use transferOperations.get.',
    )
    name: Optional[str] = Field(
        None,
        description='The server-assigned unique name. The format of `name` is `transferOperations/some/unique/name`.',
    )
    response: Optional[Dict[str, Any]] = Field(
        None,
        description='The normal response of the operation in case of success. If the original method returns no data on success, such as `Delete`, the response is `google.protobuf.Empty`. If the original method is standard `Get`/`Create`/`Update`, the response should be the resource. For other methods, the response should have the type `XxxResponse`, where `Xxx` is the original method name. For example, if the original method name is `TakeSnapshot()`, the inferred response type is `TakeSnapshotResponse`.',
    )


class Schedule(BaseModel):
    endTimeOfDay: Optional[TimeOfDay] = Field(
        None,
        description='The time in UTC that no further transfer operations are scheduled. Combined with schedule_end_date, `end_time_of_day` specifies the end date and time for starting new transfer operations. This field must be greater than or equal to the timestamp corresponding to the combintation of schedule_start_date and start_time_of_day, and is subject to the following: * If `end_time_of_day` is not set and `schedule_end_date` is set, then a default value of `23:59:59` is used for `end_time_of_day`. * If `end_time_of_day` is set and `schedule_end_date` is not set, then INVALID_ARGUMENT is returned.',
    )
    repeatInterval: Optional[str] = Field(
        None,
        description='Interval between the start of each scheduled TransferOperation. If unspecified, the default value is 24 hours. This value may not be less than 1 hour.',
    )
    scheduleEndDate: Optional[Date] = Field(
        None,
        description='The last day a transfer runs. Date boundaries are determined relative to UTC time. A job runs once per 24 hours within the following guidelines: * If `schedule_end_date` and schedule_start_date are the same and in the future relative to UTC, the transfer is executed only one time. * If `schedule_end_date` is later than `schedule_start_date` and `schedule_end_date` is in the future relative to UTC, the job runs each day at start_time_of_day through `schedule_end_date`.',
    )
    scheduleStartDate: Optional[Date] = Field(
        None,
        description="Required. The start date of a transfer. Date boundaries are determined relative to UTC time. If `schedule_start_date` and start_time_of_day are in the past relative to the job's creation time, the transfer starts the day after you schedule the transfer request. **Note:** When starting jobs at or near midnight UTC it is possible that a job starts later than expected. For example, if you send an outbound request on June 1 one millisecond prior to midnight UTC and the Storage Transfer Service server receives the request on June 2, then it creates a TransferJob with `schedule_start_date` set to June 2 and a `start_time_of_day` set to midnight UTC. The first scheduled TransferOperation takes place on June 3 at midnight UTC.",
    )
    startTimeOfDay: Optional[TimeOfDay] = Field(
        None,
        description='The time in UTC that a transfer job is scheduled to run. Transfers may start later than this time. If `start_time_of_day` is not specified: * One-time transfers run immediately. * Recurring transfers run immediately, and each day at midnight UTC, through schedule_end_date. If `start_time_of_day` is specified: * One-time transfers run at the specified time. * Recurring transfers run at the specified time each day, through `schedule_end_date`.',
    )


class TransferSpec(BaseModel):
    awsS3CompatibleDataSource: Optional[AwsS3CompatibleData] = Field(
        None, description='An AWS S3 compatible data source.'
    )
    awsS3DataSource: Optional[AwsS3Data] = Field(
        None, description='An AWS S3 data source.'
    )
    azureBlobStorageDataSource: Optional[AzureBlobStorageData] = Field(
        None, description='An Azure Blob Storage data source.'
    )
    gcsDataSink: Optional[GcsData] = Field(
        None, description='A Cloud Storage data sink.'
    )
    gcsDataSource: Optional[GcsData] = Field(
        None, description='A Cloud Storage data source.'
    )
    gcsIntermediateDataLocation: Optional[GcsData] = Field(
        None, description='Cloud Storage intermediate data location.'
    )
    httpDataSource: Optional[HttpData] = Field(
        None, description='An HTTP URL data source.'
    )
    objectConditions: Optional[ObjectConditions] = Field(
        None,
        description='Only objects that satisfy these object conditions are included in the set of data source and data sink objects. Object conditions based on objects\' "last modification time" do not exclude objects in a data sink.',
    )
    posixDataSink: Optional[PosixFilesystem] = Field(
        None, description='A POSIX Filesystem data sink.'
    )
    posixDataSource: Optional[PosixFilesystem] = Field(
        None, description='A POSIX Filesystem data source.'
    )
    sinkAgentPoolName: Optional[str] = Field(
        None,
        description='Specifies the agent pool name associated with the posix data sink. When unspecified, the default name is used.',
    )
    sourceAgentPoolName: Optional[str] = Field(
        None,
        description='Specifies the agent pool name associated with the posix data source. When unspecified, the default name is used.',
    )
    transferManifest: Optional[TransferManifest] = Field(
        None,
        description='A manifest file provides a list of objects to be transferred from the data source. This field points to the location of the manifest file. Otherwise, the entire source bucket is used. ObjectConditions still apply.',
    )
    transferOptions: Optional[TransferOptions] = Field(
        None,
        description="If the option delete_objects_unique_in_sink is `true` and time-based object conditions such as 'last modification time' are specified, the request fails with an INVALID_ARGUMENT error.",
    )


class ListOperationsResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None, description='The standard List next-page token.'
    )
    operations: Optional[List[Operation]] = Field(
        None,
        description='A list of operations that matches the specified filter in the request.',
    )


class TransferJob(BaseModel):
    creationTime: Optional[str] = Field(
        None, description='Output only. The time that the transfer job was created.'
    )
    deletionTime: Optional[str] = Field(
        None, description='Output only. The time that the transfer job was deleted.'
    )
    description: Optional[str] = Field(
        None,
        description='A description provided by the user for the job. Its max length is 1024 bytes when Unicode-encoded.',
    )
    eventStream: Optional[EventStream] = Field(
        None,
        description='Specifies the event stream for the transfer job for event-driven transfers. When EventStream is specified, the Schedule fields are ignored.',
    )
    lastModificationTime: Optional[str] = Field(
        None,
        description='Output only. The time that the transfer job was last modified.',
    )
    latestOperationName: Optional[str] = Field(
        None,
        description='The name of the most recently started TransferOperation of this JobConfig. Present if a TransferOperation has been created for this JobConfig.',
    )
    loggingConfig: Optional[LoggingConfig] = Field(
        None, description='Logging configuration.'
    )
    name: Optional[str] = Field(
        None,
        description='A unique name (within the transfer project) assigned when the job is created. If this field is empty in a CreateTransferJobRequest, Storage Transfer Service assigns a unique name. Otherwise, the specified name is used as the unique name for this job. If the specified name is in use by a job, the creation request fails with an ALREADY_EXISTS error. This name must start with `"transferJobs/"` prefix and end with a letter or a number, and should be no more than 128 characters. For transfers involving PosixFilesystem, this name must start with `transferJobs/OPI` specifically. For all other transfer types, this name must not start with `transferJobs/OPI`. Non-PosixFilesystem example: `"transferJobs/^(?!OPI)[A-Za-z0-9-._~]*[A-Za-z0-9]$"` PosixFilesystem example: `"transferJobs/OPI^[A-Za-z0-9-._~]*[A-Za-z0-9]$"` Applications must not rely on the enforcement of naming requirements involving OPI. Invalid job names fail with an INVALID_ARGUMENT error.',
    )
    notificationConfig: Optional[NotificationConfig] = Field(
        None,
        description='Notification configuration. This is not supported for transfers involving PosixFilesystem.',
    )
    projectId: Optional[str] = Field(
        None, description='The ID of the Google Cloud project that owns the job.'
    )
    schedule: Optional[Schedule] = Field(
        None,
        description='Specifies schedule for the transfer job. This is an optional field. When the field is not set, the job never executes a transfer, unless you invoke RunTransferJob or update the job to have a non-empty schedule.',
    )
    status: Optional[Status1] = Field(
        None,
        description='Status of the job. This value MUST be specified for `CreateTransferJobRequests`. **Note:** The effect of the new job status takes place during a subsequent job run. For example, if you change the job status from ENABLED to DISABLED, and an operation spawned by the transfer is running, the status change would not affect the current operation.',
    )
    transferSpec: Optional[TransferSpec] = Field(
        None, description='Transfer specification.'
    )


class TransferOperation(BaseModel):
    counters: Optional[TransferCounters] = Field(
        None, description='Information about the progress of the transfer operation.'
    )
    endTime: Optional[str] = Field(
        None, description='End time of this transfer execution.'
    )
    errorBreakdowns: Optional[List[ErrorSummary]] = Field(
        None, description='Summarizes errors encountered with sample error log entries.'
    )
    loggingConfig: Optional[LoggingConfig] = Field(
        None, description='Cloud Logging configuration.'
    )
    name: Optional[str] = Field(
        None, description='A globally unique ID assigned by the system.'
    )
    notificationConfig: Optional[NotificationConfig] = Field(
        None, description='Notification configuration.'
    )
    projectId: Optional[str] = Field(
        None, description='The ID of the Google Cloud project that owns the operation.'
    )
    startTime: Optional[str] = Field(
        None, description='Start time of this transfer execution.'
    )
    status: Optional[Status2] = Field(
        None, description='Status of the transfer operation.'
    )
    transferJobName: Optional[str] = Field(
        None,
        description='The name of the transfer job that triggers this transfer operation.',
    )
    transferSpec: Optional[TransferSpec] = Field(
        None, description='Transfer specification.'
    )


class UpdateTransferJobRequest(BaseModel):
    projectId: Optional[str] = Field(
        None,
        description='Required. The ID of the Google Cloud project that owns the job.',
    )
    transferJob: Optional[TransferJob] = Field(
        None,
        description='Required. The job to update. `transferJob` is expected to specify one or more of five fields: description, transfer_spec, notification_config, logging_config, and status. An `UpdateTransferJobRequest` that specifies other fields are rejected with the error INVALID_ARGUMENT. Updating a job status to DELETED requires `storagetransfer.jobs.delete` permission.',
    )
    updateTransferJobFieldMask: Optional[str] = Field(
        None,
        description='The field mask of the fields in `transferJob` that are to be updated in this request. Fields in `transferJob` that can be updated are: description, transfer_spec, notification_config, logging_config, and status. To update the `transfer_spec` of the job, a complete transfer specification must be provided. An incomplete specification missing any required fields is rejected with the error INVALID_ARGUMENT.',
    )


class ListTransferJobsResponse(BaseModel):
    nextPageToken: Optional[str] = Field(None, description='The list next page token.')
    transferJobs: Optional[List[TransferJob]] = Field(
        None, description='A list of transfer jobs.'
    )
